### PR TITLE
Fix `socket error: other side closed` 

### LINKED ISSUE #17: Fix `socketerror: other side closed` error when fetching major's html
When fetching a lot of majors, about 1% of them just fail because the other side closed the connection on us. This ticket will be investigating why and find the way to mitigate this.

### PR DESCRIPTION
**Pull request by rael346**
Closes #17

This PR essentially fix the `socket closed` error by 
- Refactor the scraper pipeline to do a phase for every major in one go (instead of doing every phase for individual major)
   - This means every majors' raw html will be fetched in `Classify` stage before `Tokenize`
   - Similarly every major will be `Tokenize`d before `Parse` phase 
- Add a retry logic for fetching html 
   - The refactor above already fix 99% of the errors. This is more to ensure no error of this type can happen 

Besides that there are a few improvements to the pipeline
- Improve CLI with stats for individual phase
- For business majors' concentration specifically, change the logic for fetching concentration html in `Tokenize` to getting the local html instead
   - This in turn fixed most of the error in #15, since the concentration parsed successfully in the major itself but not individually 
 - A bunch of refactor to remove unused code and make the files format more consistent (moving graduate types to just the general types folder, etc)
    - @AlpacaFur FYI, some of this might break the imports for tooling branch

### CODE REVIEW

File: src/tokenize/tokenize.ts [hunk 1]
```diff
@@ -104,12 +110,24 @@ export const tokenizeHTML = async (html: CheerioStatic) => {
 const getRequirementsContainer = ($: CheerioStatic) => {
   const tabsContainer = $("#contentarea #tabs");
   if (tabsContainer.length === 0) {
-    // had no tabs, so just look for id ending in "requirementstextcontainer"
-    const container = $("[id$='requirementstextcontainer']");
-    if (container.length === 1) {
-      return container;
+    // had no tabs, so just look for id ending in this list
+    const containers = [
```
Comment (rael346) [inline src/tokenize/tokenize.ts:114]: This is why we don't do css manually :)

File: src/main.ts [hunk 2]
```diff
@@ -1,44 +1,51 @@
...
-import { runPipeline } from "./runtime/pipeline";
-import { fatalError } from "./utils";
+import { intro, log, outro } from "@clack/prompts";
+import { EARLIEST_CATALOG_YEAR } from "./constants";
+import color from "picocolors";
+import { scrape } from "@/runtime";
+import { fatalError } from "@/utils";
+import { getCurrentYear } from "@/urls";
+
+intro(color.inverse(" Welcome to Major Scraper "));
```
Comment (AlpacaFur) [inline src/main.ts:8]: The terminal UI is really cool :)

File: src/utils.ts [hunk 3]
```diff
@@ -1,32 +1,56 @@
...
+): Promise<Result<CheerioStatic, string>> {
   try {
-    const html = cheerio.load(await wrappedGetRequest(url.href));
-    result = Ok(html);
-  } catch (error) {
-    result = Err(error);
-  }
-  return { url, result };
-};
+    const res = await fetch(url, {
```
Comment (AlpacaFur) [inline src/utils.ts:32]: fetch over unidici 👀 Is it because it works more consistently?

**Review by AlpacaFur — APPROVED** [review]
Looks awesome, thank you for all your hard work!!

File: src/utils.ts (hunk 3 above)
Comment (rael346) [reply src/utils.ts:32]: not really, `fetch` uses `undici` under the hood in `node`. Alex and Cindy used `undici` probably because they were using `node 16` and `fetch` API wasn't available until `node 18`
